### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by renaudcerrato** [hydrabus/hydrabus#2]
What's the usage license of the HydraBus hardware?

**Comment by bvernoux** [comment]
The License of the HydraBus hardware is defined here:
* https://github.com/hydrabus/hydrabus/blob/master/hardware/README.md

Extract of the README license part:
* HydraBus_1_0_Rev1_1/HydraBus_1_0_Rev1_2/HydraBus_1_0_Rev1_2plus: Hardware license [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/) (for commercial license contact info@hydrabus.com)
* HydraBus_1_0_Rev1_SoBv1_DP6037 : Hardware license [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)
* HydraBus_1_0_Shield_Template_Rev0: Hardware license [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)

**Comment by renaudcerrato** [comment]
Merci !
